import React from "react";
import { PageHeader } from "@/components/ui/PageHeader";
import { ShieldAlert, Stethoscope, Scale } from "lucide-react";

export default function DisclaimerPage() {
  return (
    <div style={{ maxWidth: 900, margin: "0 auto", display: "flex", flexDirection: "column", gap: "var(--clinova-space-6)" }}>
      <PageHeader
        title="Clinical Decision Support & Safety Disclaimer"
        subtitle="Mandatory Regulatory Disclaimers, NMC 2023 Compliance, and Emergency Protocols"
        breadcrumbs={[{ label: "Home", href: "/" }, { label: "Clinical Disclaimer" }]}
      />

      <div
        className="clinova-card"
        style={{
          borderLeft: "6px solid var(--clinova-warning)",
          backgroundColor: "var(--clinova-warning-bg)",
          display: "flex",
          flexDirection: "column",
          gap: 10,
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
          <ShieldAlert style={{ width: 22, height: 22, color: "var(--clinova-warning)" }} aria-hidden="true" />
          <h3 style={{ fontSize: "1.125rem", color: "var(--clinova-warning-text)" }}>
            NON-DIAGNOSTIC CLINICAL DECISION SUPPORT NOTICE
          </h3>
        </div>
        <p style={{ fontSize: "0.875rem", color: "var(--clinova-warning-text)", lineHeight: 1.6 }}>
          CLINOVA AI is a clinical workflow and decision-support prototype. It does not provide medical diagnoses, author prescriptions, or order invasive medical interventions autonomously.
        </p>
      </div>

      <section className="clinova-card" style={{ display: "flex", flexDirection: "column", gap: 12 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <Stethoscope style={{ width: 20, height: 20, color: "var(--clinova-accent)" }} aria-hidden="true" />
          <h3 style={{ fontSize: "1.125rem" }}>Physician Sovereignty (NMC Regulations 2023)</h3>
        </div>
        <p style={{ fontSize: "0.875rem", lineHeight: 1.6 }}>
          Under Regulations 27 and 28 of the <em>National Medical Commission (Registered Medical Practitioner) Regulations, 2023</em>, all diagnostic decisions, patient evaluations, and treatment choices remain the sole legal and ethical responsibility of the treating registered medical practitioner (RMP).
        </p>
        <p style={{ fontSize: "0.875rem", lineHeight: 1.6 }}>
          No algorithmic score, syndromic suggestion, or referral priority generated by CLINOVA AI relieves the physician or nurse of their duty to independently assess the patient.
        </p>
      </section>

      <section className="clinova-card" style={{ display: "flex", flexDirection: "column", gap: 12 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <Scale style={{ width: 20, height: 20, color: "var(--clinova-emergency)" }} aria-hidden="true" />
          <h3 style={{ fontSize: "1.125rem" }}>Emergency Resuscitation Priority (Paschim Banga Doctrine)</h3>
        </div>
        <p style={{ fontSize: "0.875rem", lineHeight: 1.6 }}>
          Pursuant to the Supreme Court of India ruling in <em>Paschim Banga Khet Mazdoor Samity v. State of West Bengal (1996)</em>, any patient presenting with acute life-threatening physiological instability must receive immediate clinical resuscitation regardless of administrative documentation, demographic completeness, or algorithmic queue status.
        </p>
      </section>
    </div>
  );
}
