"""Base classes and candidate data structures for verification rules."""

import abc
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional, List, Dict, Any, Tuple
from app.models.verification import (
    FindingSeverity,
    FindingType,
    FindingCategory,
    FindingStatus,
    ConflictType,
)
from app.services.verification.context import VerificationContext


@dataclass
class FindingCandidate:
    """A discrete clinical information verification finding generated by a rule."""
    rule_id: str
    rule_version: str
    finding_type: FindingType
    category: FindingCategory
    title: str
    description: str
    explanation: str
    severity: FindingSeverity
    field_name: Optional[str] = None
    status: FindingStatus = FindingStatus.UNRESOLVED
    is_blocking: bool = False
    expected_information: Optional[str] = None
    observed_information: Optional[str] = None
    source_evidence_ids: List[str] = field(default_factory=list)
    fact_ids: List[str] = field(default_factory=list)
    timeline_event_ids: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ConflictCandidate:
    """A detected contradictory clinical finding preserved across sources/modalities."""
    rule_id: str
    conflict_type: ConflictType
    field_name: str
    severity: FindingSeverity
    source_a_value: str
    source_b_value: str
    source_a_evidence_id: Optional[str] = None
    source_a_type: Optional[str] = None
    source_a_modality: Optional[str] = None
    source_a_timestamp: Optional[datetime] = None
    source_b_evidence_id: Optional[str] = None
    source_b_type: Optional[str] = None
    source_b_modality: Optional[str] = None
    source_b_timestamp: Optional[datetime] = None
    resolution_state: FindingStatus = FindingStatus.UNRESOLVED
    resolution_notes: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)


class BaseVerificationRule(abc.ABC):
    """Abstract base class for all modular verification rules."""
    rule_id: str = "base_rule"
    rule_version: str = "4.0.0"

    @abc.abstractmethod
    async def evaluate(
        self, context: VerificationContext
    ) -> Tuple[List[FindingCandidate], List[ConflictCandidate]]:
        """Evaluates the rule against the verification context.
        
        Returns:
            Tuple containing list of findings and list of conflicts.
        """
        pass
