"""CLINOVA AI — Versioned Prompt Templates."""

from app.ai_runtime.prompts.templates import (
    PROMPT_EXTRACTION_V1,
    PROMPT_SUMMARY_V1,
    PROMPT_FOLLOWUP_V1,
    PROMPT_TRANSLATION_V1,
    PROMPT_NORMALIZATION_V1,
    PROMPT_TRIAGE_DRAFT_V1,
    PROMPT_ADVISORY_V1,
    PROMPT_REGISTRY,
)

__all__ = [
    "PROMPT_EXTRACTION_V1",
    "PROMPT_SUMMARY_V1",
    "PROMPT_FOLLOWUP_V1",
    "PROMPT_TRANSLATION_V1",
    "PROMPT_NORMALIZATION_V1",
    "PROMPT_TRIAGE_DRAFT_V1",
    "PROMPT_ADVISORY_V1",
    "PROMPT_REGISTRY",
]
